### ISSUE TITLE
Questie(Ru)

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#10]
Перекати пожалуйста фикс под pfUI с гита авторов квести.
Спасибо.

**Comment by xVitali2** [comment]
Не понял, а что не так? Фикс миникарты?

**Comment by gamer4eg** [comment]
Да факс миникарты. Качал с гита-значки по кругу а не квадрату.

**Comment by xVitali2** [comment]
В русскую версию я добавил опцию square, так что юзай ее
