### ISSUE TITLE
Аддон добавляющий фокус(запомнить цель)

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#11]
Смотри что принес
https://github.com/wardz/FocusFrame#installation
Интересно?

**Comment by xVitali2** [comment]
Да, хорошая штука, закину

**Comment by gamer4eg** [comment]
Его бы под ру пофиксить, да шагу о нем сказать(май инглиш из вери бед)

**Comment by Monteo** [comment]
Он вроде немец

**Comment by gamer4eg** [comment]
А немеций я вообще не знаю(знаю только умное слово- умляут, во!)
Так что...Памажите пажалуста, людедобрые)
Спасибо.

**Comment by xVitali2** [comment]
пока в бете, поэтому подождем

**Comment by gamer4eg** [comment]
Уже не в бете)
