### ISSUE TITLE
[questieRU]Список багов имен кв/итем

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#12]
Если ты не против буду сюда скидывать найденные баги названий квестов итемов и всего такого прочего.
Начну пожалуй:
Линк на карте 
"Пропавшее"оборудование Ким`джаеля не отпаршено(на англ в базе)
Линк http://ru.wowhead.com/quest=5534

**Comment by xVitali2** [comment]
проверь если есть возможность

**Comment by gamer4eg** [comment]
Нету, выполнен. Надо будет мангос для тестов поднимать уже, а то несерьезно как-то)
Ядро то выложили.

**Comment by gamer4eg** [comment]
Мб и подыму...если не влом будет(кого я обманываю)
