### ISSUE TITLE
[Шрифт]pfUI

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#14]
Пофикси пожалуйста diediedie под ру.
Вот на мой- починеный
https://github.com/shagu/pfUI/issues/397

**Comment by gamer4eg** [comment]
Туда же- в DPSmate шрифт по умолчанию Accidental Presidency без ру символов.
Замени пож на дефолтный шрифт из pfUI Myriad-Pro.ttf
Нам то это заменить секунды, а нубики плачут )

**Comment by xVitali2** [comment]
пока DPSMate не меняю никак, задалбываюсь и так уже половину аддонов обновлять вручную

**Comment by gamer4eg** [comment]
Через свн хук прикрути на вто замену шрифта-делов то!

**Comment by gamer4eg** [comment]
Через post commit
