### ISSUE TITLE
[Предложение]pfUI

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#15]
Можешь добавить над неймплейтом моба иконку(прицел например) если он держит тебя в таргете?
А лучше рамочку. Танчить толпы удобнее станет. Если нужна сама иконка могу найти/сделать.

**Comment by xVitali2** [comment]
Проблема в том, что аддоны на ванилле различают мобов по имени, а если два моба стоящих рядом с тобой будут иметь одинаковые имена то будет бред, так же глючат

**Comment by gamer4eg** [comment]
разьве эта проблемма не решена уже в pfUI? Там цель моба показывает при наведении на него мышкой. Просто сравниваем этот ник с ником перса, и при true прицель на его плашку.
Или не прокатит?
