### ISSUE TITLE
[Баг][нет я не офигел][и нет не спамер]Теорикрафт

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#16]
У приста в холи спеке, после смены цели спамит ошибки-смотри скрин.
![default](https://cloud.githubusercontent.com/assets/23147230/23582423/d3679aa6-013a-11e7-8194-0f4a69b12ce5.jpg)

**Comment by gamer4eg** [comment]
Надо бы https://github.com/laytya позвать сюда кстати)

**Comment by gamer4eg** [comment]
Одно дело делаете, объединили бы репы, правда!

**Comment by xVitali2** [comment]
без приста, не могу пофиксить нормально, пробуй так

**Comment by Murkchan** [comment]
![default](https://cloud.githubusercontent.com/assets/26253455/23662068/7a8c4ad6-035f-11e7-896c-833e7df48af4.jpg)

**Comment by Murkchan** [comment]
А вообще на практике выходит, что предполагаемые значения хила в TC у пристов на Элизиуме (PvE) приуменьшены. Некоторые спелы выдают значение, на 10-25 ед больше предполагаемого  максимального. Я полагаю, на этом сервере нет разброса на шмоте c "увеличивает исцеление не более чем на N"(т.е. исц не более чем на 10 - должно быть 1-10, реально, 8-10, или просто 10), как и нет коэффициэнтов спелов.
Могу предоставить 56лвл приста для тестов.

**Comment by xVitali2** [comment]
Murkchan, а скрин кольца света без аддонов можешь скинуть?

**Comment by xVitali2** [comment]
% не должен быть между 146 и 168, если так то баг на сервере чтоли

**Comment by Murkchan** [comment]
c включеным TC
![image](https://cloud.githubusercontent.com/assets/26253455/23764398/733855f8-050e-11e7-9bc6-a6e3e3d119f7.png)
c выключенным 
![1](https://cloud.githubusercontent.com/assets/26253455/23798752/01305d12-05b7-11e7-926f-4e16b0daf1b3.jpg)

**Comment by xVitali2** [comment]
без проверки не сделаю
