### ISSUE TITLE
Адданы

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#19]
Было бы нереально круто если бы в подборку добавились такие аддоны как:
MBB (MiniMap Button Bag) - позволяет сложить все кнопки на мини-карте в одну;
enhtooltip - расширенный тултип по луту, цены в магазине и т.п. (он содержится в паке с аукционером который нафиг не нужен, вроде требует Stubby) можно тут глянуть https://github.com/Logonz/Auctioneer-3-9-0-1260-beta-1.12.1
MobHealth3 - показывает здоровье мобов в цифирках
Mobinfo2 - расширенное инфо по мобу в тултипе, так же запоминает что лутается с мобу
ZHunterMod (этот опционально так как профильный остальные вроде всем бы пригодились)
npcscan

еще вопрос по аддону Automation: есть аддон похожего толка https://github.com/satan666/_LP сравнить бы их, какой из них лучше?

Заранее премного благодарен :)

**Comment by xVitali2** [comment]
enhtooltip стоит в informant аддоне
остальное может быть

**Comment by gamer4eg** [comment]
MBB  на руклиенте не работает нормально.
Соник пофиксил https://github.com/laytya/MinimapButtonBag-vanilla
MobHealth3 поддержу
Остальное на любителя.
Про аутоматон и лази - пользуюсь обоими, тк у одного некоторые функции удобнее чем у другого.
АЛСО кас у тебя в автоматоне продажа серого по одному?(Не дизконектит?)

**Comment by leokem** [comment]
MBB у Соника и брал кстати, вроде ном работает на ру клиенте

**Comment by xVitali2** [comment]
Продаю через garbagеfu поэтому автоматоном уже не пользуюсь, а так да, дисконило
