### ISSUE TITLE
[Bug][Postal]

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#20]
У аддона постал, как и ct_mailmod есть глючок при отправке письма с аттачем вставляет название аттача в тему и если строка в теме получается длинная письмо уходит без аттача, а при условии если оправляется очередь из писем, вместо нескольких писем отправляется одно, без аттача и аддон пишет ошибку

**Comment by xVitali2** [comment]
сколько не пробую, в тему ничего сам не вставляет, что я делаю не так?

**Comment by leokem** [comment]
так он добавляет тему во время отправки, когда аттай просто добавляешь в тему ни чего не вставляется

**Comment by xVitali2** [comment]
так почему ты отправляешь письмо без названия темы)

**Comment by leokem** [comment]
ну на сколько я понимаю, когда формируешь пачку писем, посталу пофиг что ты вставишь в тему, он сам вставляет название аттача в тему при формировании каждого письма
