### ISSUE TITLE
[Questie][Bug?]

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#21]
Вчера столкнулся с глюком, в десолейс брал квесты на репу с кентаврами (там два война стоят, выдают репутационные квесты с разными племенами) квесты взять не смог, выдет какое-то пустое прозрачное окно, пока аддон не отключил квест так и не смог взять

**Comment by dakotarisen** [comment]
![novy_tochechny_risunok](https://cloud.githubusercontent.com/assets/25033779/23990240/7c407422-0a46-11e7-821f-afcd92d720d1.jpg)
Постоянно вылетает эта ошибка

**Comment by leokem** [comment]
в общем на данный момент аддон не дает принимать некоторые квесты, иногда его переклинивает при получении квестового лута с мобов

**Comment by xVitali2** [comment]
отписываем какой именно квест, буду смотреть
