### ISSUE TITLE
QuestieRU

### ISSUE THREAD

**Issue by dakotarisen** [KasVital/Addons-for-Vanilla-1.12.1-CFM#22]
Не отображаются квестовые тултипы на квестовых npc

**Comment by xVitali2** [comment]
![image](https://cloud.githubusercontent.com/assets/15636669/24107446/c6c5fcd0-0d9b-11e7-9da6-a3a208723d1f.png)
всё показывает, точнее пиши

**Comment by dakotarisen** [comment]
Провел маленький анализ,не показывает только при тултипе на курсор мышки(pfui)
![1](https://cloud.githubusercontent.com/assets/25033779/24125329/398733f0-0dd9-11e7-89fb-26c218335628.jpg)
![2](https://cloud.githubusercontent.com/assets/25033779/24125331/3b53e3e0-0dd9-11e7-998a-de60ca51e2b1.jpg)

**Comment by xVitali2** [comment]
Ну теперь только так, англ версия сомневаюсь что показывает

**Comment by dakotarisen** [comment]
Так буквально недавно все показывало,когда впервые залил 3.70

**Comment by xVitali2** [comment]
be0d39ca81b789205d49b81cc8d37adff23288f7
