### ISSUE TITLE
Идея по QuestieRU

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#24]
А почему бы тебе не прикрутить проверку локали к руквести, и если локаль НЕ ру-НЕ запускаться аддону.Как бы и все.А, если установлен англ квести если локаль НЕ англ то и его не запускать.
Решило бы проблемму постоянного тыкания галочек в меню аддонов.

**Comment by xVitali2** [comment]
зачем делать такой гемор, если можно просто удалить квести который не нужен
