### ISSUE TITLE
QuestieRU[tooltips]

### ISSUE THREAD

**Issue by dakotarisen** [KasVital/Addons-for-Vanilla-1.12.1-CFM#25]
Глюки в обновлении квестовых задач в тултипе на курсор мышки.
![default](https://cloud.githubusercontent.com/assets/25033779/24289362/0817e47a-1092-11e7-896f-d04cd1689e68.jpg)

**Comment by xVitali2** [comment]
Эту проблему я не решаю, они вообще отключили эти подсказки на англ версии, значит не зря

**Comment by dakotarisen** [comment]
Понял,спасибо большое за ответ.

**Comment by xVitali2** [comment]
сейчас все подсказки не обновляются, ждем решения от авторов

**Comment by xVitali2** [comment]
трекер пофиксили, надеюсь скоро и подсказки обновят
