### ISSUE TITLE
Postal[new version]

### ISSUE THREAD

**Issue by dakotarisen** [KasVital/Addons-for-Vanilla-1.12.1-CFM#26]
Вылетает куча ошибок(279,518,616 и тд.),ссылающихся на postal.lua
![default](https://cloud.githubusercontent.com/assets/25033779/24291249/34155b28-1099-11e7-93a2-2e0f7be221d5.jpg)

**Comment by xVitali2** [comment]
Да сейчас проверю

**Comment by xVitali2** [comment]
там с маленькой буквы теперь весь постал, перекачай

**Comment by dakotarisen** [comment]
Заработало
