### ISSUE TITLE
postal

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#27]
по правой клавише, почему то, вещи перестали перемещаться в отправку, раньше работало, очень удобно было

**Comment by xVitali2** [comment]
всё работает. не отправляются, а просто же выкладываются в отправку, так?

**Comment by leokem** [comment]
в том и дело что не выкладываются, если перетащить мышкой то все норм, но если правой клавишей в сумке нажать, то не выкладываются в отправку

**Comment by xVitali2** [comment]
у меня работает, смотри не так что-то установил
удали и заново поставь аддон
