### ISSUE TITLE
Autimaton

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#30]
Можешь пожалуйста починить продажу у аутоматона?(Чтобы продавал по 1 итему с задержкой)
А еще можешь добавить авто удаление предметов по названию (а то достало стрелы от селеров руками удалять, а еще черные алмазы и т д).

**Comment by xVitali2** [comment]
Автоматом трогать не буду
ты возвращай стрелы обратно
