### ISSUE TITLE
[предложение]SmartHeal

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#33]
Слушай а можешь в команд лист смартхила добавить вызов автоцели (три команды соответственно) спасибо.

**Comment by gamer4eg** [comment]
А еще смотри что нашел https://github.com/theoden-dd/gatherer_p2p
С синхронизаций, добавишь p2p в совой?

**Comment by xVitali2** [comment]
если не видел, то gatherer уже давно с этой фишкой, только он кидает английскими названиями

**Comment by xVitali2** [comment]
про автоцель не понял

**Comment by gamer4eg** [comment]
В смартхиле третья вкладка автоматический выбор цели и заклинания, но он только назначается на клавишу(в настройках) можешь сделать чтобы его можно было вызвать еще и командой в макросе?
А так же не хватает назначения приоритета на определенного игрока(по нику) в приоритетах.
Сейчас наглядных картинок подкину, вижу сам ты им не пользуешься)
![image](https://cloud.githubusercontent.com/assets/23147230/25046848/5967378a-213c-11e7-85f6-10e595b7a899.png)
А так же от себя добавлю что еще номер группы выбирать(где строчка группа) 1-8
И ты это, извини что так накидал идей, просто хилы в рейде дорвались до этого аддона...=(

**Comment by xVitali2** [comment]
а ок

**Comment by xVitali2** [comment]
проверяй

**Comment by gamer4eg** [comment]
Работает, спасибо большее!
А про приоритеты займешься?

**Comment by gamer4eg** [comment]
Кстати опять же не в тему но можешь в LazyScript добавить оператор ввода макроса прямо из поля лейзи?А то создавать тысячи макросов на одну строчку-уныло...

**Comment by xVitali2** [comment]
Lazy делать не буду
а по нику, будет время займусь

**Comment by gamer4eg** [comment]
По нику подробнее изложу что желательно-хилов наших опросил.
Добавление (при надобности) больше 1 приоритета по нику(если танка два например и т д)
Выбор номера группы в приоритетах(сейчас строго группа игрока)
Прерывание каста при нажатии кнопки ЕСЛИ цель хилить УЖЕ не надо(похилили уже другие). НО не ранее завершения гкд(тк прерывать раньше отката ГКД нет смысла)
В идеале(думаю это уж точно влом) работа с хилкомом(учет значений из него).
Класный аддон однако, но сырой... Накуя я его хилам показал...
