### ISSUE TITLE
[Баг]BetterCharacterStats

### ISSUE THREAD

**Issue by Murkchan** [KasVital/Addons-for-Vanilla-1.12.1-CFM#34]
BetterCharacterStats ошибку изредка бьет
![default](https://cloud.githubusercontent.com/assets/26253455/25053862/9567c292-2162-11e7-900b-0c2cfb8bf795.png)

**Comment by xVitali2** [comment]
Нет такого аддона

**Comment by Murkchan** [comment]
Извини, не туда)
