### ISSUE TITLE
Реквестирую мануал по адаптации других аддонов для поддержки зависимостей из !Libs

### ISSUE THREAD

**Issue by byaka** [KasVital/Addons-for-Vanilla-1.12.1-CFM#35]
Пытаюсь заставить работать пару плагинов к FuBar, но они хотят иметь зависимости в корне и подключать их через директиву `## Dependencies:`. Разводить дублирование аддонов не хочется, хочу сделать корректно.

**Comment by byaka** [comment]
эм? хоть причину закрытия сообщите..

**Comment by xVitali2** [comment]
Посмотри как сделал tankpointsfu например, по-другому никак, если я тебя правильно понял
