### ISSUE TITLE
[bug]QuestieRu

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#36]
Установил свежий QuestieRU из пака, и обновил папку !Libs из пака, вылезает ошибка:
![world of warcraft 10 15 2017 - 10 42 05 01](https://user-images.githubusercontent.com/2864452/31582835-e787d1f6-b196-11e7-9e00-b474e1efdc76.png)
и аддон не загружается, либо не работает, потому как на карте меток нет и квест лог не появляется

**Comment by leokem** [comment]
убрал лишнюю запятую в указанной строке, вроде заработало.

**Comment by xVitali2** [comment]
да, сорян, все правильно ты сделал
исправлено
