### ISSUE TITLE
[bug] QuestieRu фриз

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#37]
после убиства мобов по квесту на убийство происходит фриз, если квести отключить то фриз пропадает

**Comment by gamer4eg** [comment]
Памяти больше выделить на аддоны пробовал? Игра в оконном режиме?

**Comment by leokem** [comment]
памяти выделенно 256мб, игра в оконном режиме

**Comment by xVitali2** [comment]
у меня не фризит... какой квест был?

**Comment by leokem** [comment]
в унгоро квест на убийство птеродактелей фиряющих, не помню как они называются...

**Comment by leokem** [comment]
сегодня наблюдал в силитусе такую же фигню на квестах с сумеречным молотом, убить геологов, собрать тексты и т.п.

**Comment by xVitali2** [comment]
понял в чём проблема, много значков на карте устанавливает и начинает фризить когда quesie обновляется, попробую уменьшить число значков
