### ISSUE TITLE
[bug]postal

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#38]
после последнего обновления аддон выдает следующую ошибку:
![wow_ru screenshot 2017 11 06 - 10 02 03 38](https://user-images.githubusercontent.com/2864452/32429072-0d8ce298-c2da-11e7-8df6-52271f5acf42.png)

**Comment by leokem** [comment]
какие-то не понятные проблемы связанные с названием проекта (большая/маленькая буквы)... удалил, папку с аддоном и файлы, связанные с аддоном, из папки savedvariables, скопировал папку с аддоном из свежескачанного архива и ошибка пропала

**Comment by xVitali2** [comment]
правильно сделал
т.к. просто обновить не получится, автор аддона сменил название аддона полностью на строчные буквы, поэтому такая ошибка и вылетала
