### ISSUE TITLE
Проблема c Gatherer

### ISSUE THREAD

**Issue by Vitoshka** [KasVital/Addons-for-Vanilla-1.12.1-CFM#39]
После установки обновлённого Gatherer, стала появляться данная ошибка:

[2017/11/14 22:47:18-1247]: Gatherer\GatherBroadcast.lua:5: assertion failed!
<in C code>: in function `assert'
Gatherer\GatherBroadcast.lua:5: in function `Gatherer_BroadcastGather'
Gatherer\Gatherer.lua:779: in function `Gatherer_TimeCheck'
<string>:"Gatherer:OnUpdate":2: in main chunk

  ---

**Comment by xVitali2** [comment]
сбрось настройки gatherer или выключи р2р /gatherer p2p

**Comment by xVitali2** [comment]
кстати на русском клиенте ошибка?

**Comment by Vitoshka** [comment]
На английском клиенте.

**Comment by xVitali2** [comment]
И что до сих пор?
