### ISSUE TITLE
[bug] QuestieRU 

### ISSUE THREAD

**Issue by leokem** [KasVital/Addons-for-Vanilla-1.12.1-CFM#40]
взял квест в дарнасе и вылез баг на скрине который, самое печальное что окошко не закрывается, спасает только improoved error frame
![desktop screenshot 2017 11 23 - 13 25 49 31](https://user-images.githubusercontent.com/2864452/33168557-658f89b6-d052-11e7-9172-796c066ee52f.png)

**Comment by xVitali2** [comment]
исправил, спасиб
