### ISSUE TITLE
Informant

### ISSUE THREAD

**Issue by shikulja** [KasVital/Addons-for-Vanilla-1.12.1-CFM#49]
Встроенный EnhTooltip (и Stubby как зависимость) ломает внешний EnhTooltip как зависимость Auctioneer который ее требует (ломается тоже скорее всего)
Придется отвязывать и использовать независимо

скину отвязанную версию и зависимости и опциональные чтобы не искать. Auctioneer вроде свежий, но сильно не искал
[EnhTooltip 3.9.0.zip](https://github.com/KasVital/Addons-for-Vanilla-1.12.1-CFM/files/14085889/EnhTooltip.3.9.0.zip)
[Informant 3.9.0.zip](https://github.com/KasVital/Addons-for-Vanilla-1.12.1-CFM/files/14085890/Informant.3.9.0.zip)
[Stubby 3.9.0.zip](https://github.com/KasVital/Addons-for-Vanilla-1.12.1-CFM/files/14085892/Stubby.3.9.0.zip)
[Auctioneer 3.9.1063.zip](https://github.com/KasVital/Addons-for-Vanilla-1.12.1-CFM/files/14085894/Auctioneer.3.9.1063.zip)

то есть формально работает, но если потребуется аукционер, у которого не переделаны зависимости от этого Informant то он будет баговать. Тут либо привязывать вообще все в один аддон, что не очень правильно. Либо не привязывать их все, так как у них всех внешняя зависимость друг от друга

**Comment by xVitali2** [comment]
аукционер устарел, советую использовать aux

**Comment by shikulja** [comment]
знаю, но ломается на ровном месте из-за пустяка. аукционер я например не использовал, только EnhTooltip и он конфликтовал с Informant.. как оказалось что он уже был встроен..

**Comment by xVitali2** [comment]
EnhTooltip разве где-то еще используется кроме как аукционера с информантом?

**Comment by shikulja** [comment]
Скорее всего нет, использовал как альтернативу другим тултиперам
