### ISSUE TITLE
[Предложение]NotGrid

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#5]
Слушай, а можешь обновить ру версию NotGrid ?
Автор тут обновил https://github.com/gnwl/NotGrid
Старая ру версия тут(или с яд ругруппы) https://drive.google.com/file/d/0B2RWjLl8UkfxeXRUcU12RlVoalk/view

**Comment by xVitali2** [comment]
Хорошо, посмотрю

**Comment by xVitali2** [comment]
готово a3ad8dac578afe2683a21c4c98bf33ac909b9c97
