### ISSUE TITLE
SmartHeal

### ISSUE THREAD

**Issue by gamer4eg** [KasVital/Addons-for-Vanilla-1.12.1-CFM#7]
Слушай, а можешь пофиксить SmartHeal чтобы он с Notgrid работал?

**Comment by xVitali2** [comment]
Нотгрид не использую, поэтому в ближайшем будущем нет

**Comment by gamer4eg** [comment]
Жаль.Принято.А то просто девушка юзает)
Попробую мауса попросить.

**Comment by xVitali2** [comment]
а разве на англ версии они совместимы?

**Comment by gamer4eg** [comment]
Нет. Но я заметил ты делаешь фиксы, думал будет интересно. Там та же проблемма что с clicue нужны строки для связи интерфейсов в гриде скорее всего. Ну или в смартхиле. Он именно не считает грид интерфейсом группы/рейда.
